#output_prefix: SABER_miseq1
#input_prefix: fastq.miseq1

#output_prefix: SABER_miseq2
#input_prefix: fastq.miseq2

output_prefix: SABER_nextseq1
input_prefix: fastq.nextseq1

use_umi: true
variant_read_cutoff: 5000
